version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app  # Mount local project folder into the container
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables hot reloading in Docker
    command: ["npm", "run", "dev"]
